/**
 * Document Processing Pipeline
 * Handles the actual document generation through Claude API
 */

import * as fs from 'fs/promises'
import * as path from 'path'
import { ClaudeAPIClient } from './ClaudeAPIClient'

export interface Document {
  path: string
  content: string
  metadata: {
    type: string
    size: number
    processed: Date
  }
}

export type ProgressCallback = (progress: number, operation: string) => void

export class DocumentPipeline {
  private claude: ClaudeAPIClient
  private projectType: string = 'unknown'

  constructor(config: any) {
    this.claude = new ClaudeAPIClient(config.claudeApiKey || process.env.CLAUDE_API_KEY)
  }

  /**
   * Set project type for context
   */
  setProjectType(type: string): void {
    this.projectType = type
  }

  /**
   * Process a single file through the pipeline
   */
  async process(filePath: string, onProgress?: ProgressCallback): Promise<Document> {
    try {
      // Step 1: Read file
      onProgress?.(10, 'reading')
      const content = await fs.readFile(filePath, 'utf-8')
      const stats = await fs.stat(filePath)
      
      // Step 2: Analyze file type
      onProgress?.(20, 'analyzing')
      const fileType = this.detectFileType(filePath)
      
      // Step 3: Prepare context
      onProgress?.(30, 'preparing')
      const context = this.prepareContext(filePath, fileType)
      
      // Step 4: Generate documentation
      onProgress?.(50, 'generating')
      const documentation = await this.generateDocumentation(content, context, fileType)
      
      // Step 5: Format output
      onProgress?.(80, 'formatting')
      const formatted = this.formatDocumentation(documentation, filePath)
      
      // Step 6: Create document
      onProgress?.(100, 'complete')
      return {
        path: filePath,
        content: formatted,
        metadata: {
          type: fileType,
          size: stats.size,
          processed: new Date()
        }
      }
      
    } catch (error) {
      throw new Error(`Pipeline failed for ${filePath}: ${error.message}`)
    }
  }

  /**
   * Detect file type from extension
   */
  private detectFileType(filePath: string): string {
    const ext = path.extname(filePath).toLowerCase()
    const typeMap: Record<string, string> = {
      '.ts': 'TypeScript',
      '.tsx': 'TypeScript React',
      '.js': 'JavaScript',
      '.jsx': 'JavaScript React',
      '.py': 'Python',
      '.go': 'Go',
      '.rs': 'Rust',
      '.java': 'Java',
      '.md': 'Markdown',
      '.json': 'JSON',
      '.yaml': 'YAML',
      '.yml': 'YAML'
    }
    return typeMap[ext] || 'Unknown'
  }

  /**
   * Prepare context for documentation
   */
  private prepareContext(filePath: string, fileType: string): string {
    const fileName = path.basename(filePath)
    const dirName = path.dirname(filePath)
    
    return `
File: ${fileName}
Path: ${dirName}
Type: ${fileType}
Project Type: ${this.projectType}
    `.trim()
  }

  /**
   * Generate documentation using Claude
   */
  private async generateDocumentation(
    content: string,
    context: string,
    fileType: string
  ): Promise<string> {
    const prompt = `
Generate comprehensive documentation for the following ${fileType} code.
Include:
1. Overview and purpose
2. Key functions/classes/components
3. Dependencies and imports
4. Usage examples where appropriate
5. Important implementation details

Context:
${context}

Code:
\`\`\`${fileType.toLowerCase()}
${content}
\`\`\`

Generate the documentation in Markdown format.
    `.trim()

    return await this.claude.generateDocumentation(prompt)
  }

  /**
   * Format documentation with metadata
   */
  private formatDocumentation(documentation: string, filePath: string): string {
    const fileName = path.basename(filePath)
    const timestamp = new Date().toISOString()
    
    return `# Documentation: ${fileName}

*Generated: ${timestamp}*

---

${documentation}

---

*This documentation was automatically generated by DocuMentor*
`
  }
}