/**
 * Output Manager
 * Handles saving and organizing generated documentation
 */

import * as fs from 'fs/promises'
import * as path from 'path'
import { Document } from './DocumentPipeline'

export class OutputManager {
  private outputPath: string
  private tempPath: string

  constructor(outputPath: string) {
    this.outputPath = outputPath
    this.tempPath = path.join(outputPath, '.temp')
  }

  /**
   * Initialize output directories
   */
  async initialize(): Promise<void> {
    await fs.mkdir(this.outputPath, { recursive: true })
    await fs.mkdir(this.tempPath, { recursive: true })
  }

  /**
   * Save a document
   */
  async save(document: Document): Promise<void> {
    // Create output file path
    const relativePath = path.relative(process.cwd(), document.path)
    const outputFile = path.join(
      this.outputPath,
      relativePath.replace(/\.[^.]+$/, '.md')
    )

    // Ensure directory exists
    await fs.mkdir(path.dirname(outputFile), { recursive: true })

    // Save document
    await fs.writeFile(outputFile, document.content, 'utf-8')
  }

  /**
   * Save processing report
   */
  async saveReport(report: any): Promise<void> {
    const reportPath = path.join(this.outputPath, 'PROCESSING_REPORT.md')
    const content = this.formatReport(report)
    await fs.writeFile(reportPath, content, 'utf-8')
  }

  /**
   * Format report as markdown
   */
  private formatReport(report: any): string {
    return `# Documentation Processing Report

Generated: ${new Date().toISOString()}

## Summary

- **Total Files**: ${report.summary.totalFiles}
- **Processed**: ${report.summary.processed}
- **Failed**: ${report.summary.failed}
- **Duration**: ${report.summary.duration}
- **Rate**: ${report.summary.rate}

## Errors

${report.errors.length > 0 ? report.errors.map((e: string) => `- ${e}`).join('\n') : 'No errors encountered'}

---

*Report generated by DocuMentor*
`
  }

  /**
   * Validate output files
   */
  async validate(): Promise<boolean> {
    try {
      const files = await this.listOutputFiles()
      for (const file of files) {
        const content = await fs.readFile(file, 'utf-8')
        if (content.length < 100) {
          return false // Too short, likely invalid
        }
      }
      return true
    } catch {
      return false
    }
  }

  /**
   * List all output files
   */
  private async listOutputFiles(): Promise<string[]> {
    const files: string[] = []
    
    async function scan(dir: string): Promise<void> {
      const entries = await fs.readdir(dir, { withFileTypes: true })
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name)
        if (entry.isDirectory() && entry.name !== '.temp') {
          await scan(fullPath)
        } else if (entry.isFile() && entry.name.endsWith('.md')) {
          files.push(fullPath)
        }
      }
    }
    
    await scan(this.outputPath)
    return files
  }

  /**
   * Cleanup temporary files
   */
  async cleanup(): Promise<void> {
    try {
      await fs.rm(this.tempPath, { recursive: true, force: true })
    } catch {
      // Ignore cleanup errors
    }
  }

  /**
   * Finalize output
   */
  async finalize(): Promise<void> {
    // Create index file
    const indexPath = path.join(this.outputPath, 'INDEX.md')
    const files = await this.listOutputFiles()
    
    const indexContent = `# Documentation Index

Generated: ${new Date().toISOString()}

## Files

${files.map(f => `- [${path.basename(f)}](${path.relative(this.outputPath, f)})`).join('\n')}

Total: ${files.length} documents
`
    
    await fs.writeFile(indexPath, indexContent, 'utf-8')
  }
}